In [4]:
import pandas as pd

In [5]:
url = "https://en.wikipedia.org/wiki/List_of_capitals_in_the_United_States"
# url = "https://cnn.com"

In [6]:
tables = pd.read_html(url)
tables

[                                           0   \
 0                                       State
 1   Municipal (Within city proper boundaries)
 2                                     Alabama
 3                                      Alaska
 4                                     Arizona
 5                                    Arkansas
 6                                  California
 7                                    Colorado
 8                                 Connecticut
 9                                    Delaware
 10                                    Florida
 11                                    Georgia
 12                                     Hawaii
 13                                      Idaho
 14                                   Illinois
 15                                    Indiana
 16                                       Iowa
 17                                     Kansas
 18                                   Kentucky
 19                                  Louisiana
 20                                      Maine
 21                                   Maryland
 22                              Massachusetts
 23                                   Michigan
 24                                  Minnesota
 25                                Mississippi
 26                                   Missouri
 27                                    Montana
 28                                   Nebraska
 29                                     Nevada
 30                              New Hampshire
 31                                 New Jersey
 32                                 New Mexico
 33                                   New York
 34                             North Carolina
 35                               North Dakota
 36                                       Ohio
 37                                   Oklahoma
 38                                     Oregon
 39                               Pennsylvania
 40                               Rhode Island
 41                             South Carolina
 42                               South Dakota
 43                                  Tennessee
 44                                      Texas
 45                                       Utah
 46                                    Vermont
 47                                   Virginia
 48                                 Washington
 49                              West Virginia
 50                                  Wisconsin
 51                                    Wyoming

                                                    1              2   \
 0                                                Abr.     State-hood
 1   Metropolitan (Both within the capital city pro...  Rank in state
 2                                                  AL           1819
 3                                                  AK           1959
 4                                                  AZ           1912
 5                                                  AR           1836
 6                                                  CA           1850
 7                                                  CO           1876
 8                                                  CT           1788
 9                                                  DE           1787
 10                                                 FL           1845
 11                                                 GA           1788
 12                                                 HI           1959
 13                                                 ID           1890
 14                                                 IL           1818
 15                                                 IN           1816
 16                                                 IA           1846
 17                                                 KS           1861
 18                                                 KY           1792
 19                                                 LA           1812
 20                                                 ME           1820
 21                                                 MD           1788
 22                                                 MA           1788
 23                                                 MI           1837
 24                                                 MN           1858
 25                                                 MS           1817
 26                                                 MO           1821
 27                                                 MT           1889
 28                                                 NE           1867
 29                                                 NV           1864
 30                                                 NH           1788
 31                                                 NJ           1787
 32                                                 NM           1912
 33                                                 NY           1788
 34                                                 NC           1789
 35                                                 ND           1889
 36                                                 OH           1803
 37                                                 OK           1907
 38                                                 OR           1859
 39                                                 PA           1787
 40                                                 RI           1790
 41                                                 SC           1788
 42                                                 SD           1889
 43                                                 TN           1796
 44                                                 TX           1845
 45                                                 UT           1896
 46                                                 VT           1791
 47                                                 VA           1788
 48                                                 WA           1889
 49                                                 WV           1863
 50                                                 WI           1848
 51                                                 WY           1890

                 3              4           5                  6        7   \
 0          Capital  Capital since  Area (miÂ²)  Population (2010)    Notes
 1       Rank in US            NaN         NaN                NaN      NaN
 2       Montgomery           1846       155.4             205764   374536
 3           Juneau           1906      2716.7              31275      NaN
 4          Phoenix           1889       474.9            1445632  4192887
 5      Little Rock           1821       116.2             193524   877091
 6       Sacramento           1854        97.2             466488  2527123
 7           Denver           1867       153.4             600158  2552195
 8         Hartford           1875        17.3             124775  1212381
 9            Dover           1777        22.4              36047   162310
 10     Tallahassee           1824        95.7             190894   379627
 11         Atlanta           1868       131.7             420003  5789700
 12        Honolulu           1845        85.7             337256   953207
 13           Boise           1865        63.8             205671   616561
 14     Springfield           1837        54.0             116250   208182
 15    Indianapolis           1825       361.5             829718  1756221
 16      Des Moines           1857        75.8             203433   580255
 17          Topeka           1856        56.0             127473   230824
 18       Frankfort           1792        14.7              25527    70758
 19     Baton Rouge           1880        76.8             229553   802484
 20         Augusta           1832        55.4              19136   117114
 21       Annapolis           1694        6.73              38394      NaN
 22          Boston           1630        48.4             617594  4522858
 23         Lansing           1847        35.0             114297   464036
 24      Saint Paul           1849        52.8             300851  3502891
 25         Jackson           1821       104.9             173514   539057
 26  Jefferson City           1826        27.3              43079   149807
 27          Helena           1875        14.0              28190    74801
 28         Lincoln           1867        74.6             258379   302157
 29     Carson City           1861       143.4              55274      NaN
 30         Concord           1808        64.3              42695      NaN
 31         Trenton           1784        7.66              84913   366513
 32        Santa Fe           1610        37.3              75764   183732
 33          Albany           1797        21.4              97856   857592
 34         Raleigh           1792       114.6             403892  1130490
 35        Bismarck           1883        26.9              61272   108779
 36        Columbus           1816       210.3             822553  1967066
 37   Oklahoma City           1910       607.0             580000  1252987
 38           Salem           1855        45.7             154637   390738
 39      Harrisburg           1812        8.11              49528   647390
 40      Providence           1900        18.5             178042  1630956
 41        Columbia           1786       125.2             131686   913797
 42          Pierre           1889        13.0              13646      NaN
 43       Nashville           1826       473.3             635710  1582264
 44          Austin           1839       251.5             790390  1716291
 45  Salt Lake City           1858       109.1             186440  1124197
 46      Montpelier           1805        10.2               7855      NaN
 47        Richmond           1780        60.1             204214  1231675
 48         Olympia           1853        16.7              46478   234670
 49      Charleston           1885        31.6              51400   304214
 50         Madison           1838        68.7             233209   561505
 51        Cheyenne           1869        21.1              59466    91738

       8      9                                                  10
 0    NaN    NaN                                                NaN
 1    NaN    NaN                                                NaN
 2    2.0  115.0            Birmingham is the state's largest city.
 3    3.0    NaN  Largest capital by municipal land area. Anchor...
 4    1.0    5.0  Most populous U.S. state capital and the only ...
 5    1.0  117.0                                                NaN
 6    6.0   35.0  Supreme Court of California is headquartered i...
 7    1.0   19.0          Denver was called Denver City until 1882.
 8    3.0  221.0  Bridgeport is the state's largest city. Hartfo...
 9    2.0    NaN  Longest-serving capital in terms of statehood....
 10   7.0  126.0  Jacksonville is the largest city. Miami is the...
 11   1.0   38.0  State capital with the most populous metro are...
 12   1.0   55.0                                                NaN
 13   1.0   99.0                                                NaN
 14   6.0  241.0  Springfield was once home to Abraham Lincoln. ...
 15   1.0   15.0                                                NaN
 16   1.0  102.0                                                NaN
 17   4.0  217.0  Wichita is the state's largest city. The large...
 18  14.0    NaN            Louisville is the state's largest city.
 19   2.0   97.0  New Orleans is the state's largest city and ho...
 20   8.0    NaN  Portland is the state's largest city and previ...
 21   7.0    NaN  Smallest capital by land area. Baltimore is th...
 22   1.0   22.0   Longest continuously serving capital in the U.S.
 23   5.0  239.0  Only state capital that is not also its county...
 24   2.0   64.0  Capital's twin city, Minneapolis, is the state...
 25   1.0  149.0  Only state capital that shares its status as c...
 26  15.0    NaN  Kansas City is the state's largest city, and G...
 27   6.0    NaN              Billings is the state's largest city.
 28   2.0   71.0  Omaha is the state's largest city. It shares t...
 29   6.0    NaN  One of two independent cities that serves as a...
 30   3.0    NaN            Manchester is the state's largest city.
 31  10.0    NaN  Served as the U.S. capital for a short period ...
 32   4.0    NaN  Longest serving capital in the United States. ...
 33   6.0    NaN         New York City is the state's largest city.
 34   2.0   41.0             Charlotte is the state's largest city.
 35   2.0    NaN                 Fargo is the state's largest city.
 36   1.0   14.0  Third-largest state capital; however, the Cinc...
 37   1.0   27.0            Shortest serving current state capital.
 38   3.0  151.0              Portland is the state's largest city.
 39   9.0    NaN          Philadelphia is the state's largest city.
 40   1.0  137.0  Also served as the state's capital 1636â1686 a...
 41   2.0  199.0  Charleston is the state's largest city, while ...
 42   8.0    NaN           Sioux Falls is the state's largest city.
 43   1.0   24.0                                                NaN
 44   4.0   11.0  Houston is the state's largest city and the pr...
 45   1.0  123.0                                                NaN
 46   6.0    NaN  Least populous U.S. state capital. Burlington ...
 47   4.0   98.0  Virginia Beach and Norfolk are the state's lar...
 48  24.0    NaN               Seattle is the state's largest city.
 49   1.0    NaN  Charleston is the smallest capital city that i...
 50   2.0   82.0             Milwaukee is the state's largest city.
 51   1.0    NaN                                                NaN  ,
                           0     1     2                 3                  4  \
 0              Insular area  Abr.  Date           Capital  Population (2010)
 1            American Samoa    AS  1899         Pago Pago               3656
 2                      Guam    GU  1898           HagÃ¥tÃ±a               1051
 3  Northern Mariana Islands    MP  1947            Saipan               1028
 4               Puerto Rico    PR  1898          San Juan             395326
 5       U.S. Virgin Islands    VI  1917  Charlotte Amalie              18481

                                                    5
 0                                              Notes
 1  Pago Pago refers to both a village and a group...
 2              Dededo is the area's largest village.
 3                                                NaN
 4  The city of San Juan was originally called Pue...
 5                                                NaN  ,
                                            0  \
 0                                      State
 1               Alabama[13]Statehood in 1819
 2                                   Savannah
 3                                       1755
 4                                       1776
 5                               Augusta (GA)
 6                          Heard's Fort (GA)
 7                               Augusta (GA)
 8                              Savannah (GA)
 9                              Ebenezer (GA)
 10                             Savannah (GA)
 11                              Augusta (GA)
 12                           Louisville (GA)
 13                              Natchez (MS)
 14                           Washington (MS)
 15                              St. Stephens
 16                                Huntsville
 17                                   Cahawba
 18                                Tuscaloosa
 19                                Montgomery
 20               Alaska[15]Statehood in 1959
 21                                      1867
 22                                      1900
 23                                    Juneau
 24                                      1912
 25                                      1959
 26              Arizona[16]Statehood in 1912
 27                                      1850
 28                              Mesilla (NM)
 29                          San Antonio (TX)
 ..                                       ...
 445                                     1776
 446                                 Richmond
 447          Washington[46]Statehood in 1889
 448                         Oregon City (OR)
 449                                     1848
 450                               Salem (OR)
 451                                  Olympia
 452                                     1889
 453           West VirginiaStatehood in 1863
 454  Middle Plantation (VA)Williamsburg (VA)
 455                                     1707
 456                                     1776
 457                            Richmond (VA)
 458                                 Wheeling
 459                                     1863
 460                               Charleston
 461                                 Wheeling
 462                               Charleston
 463           Wisconsin[47]Statehood in 1848
 464                           Vincennes (IN)
 465                           Kaskaskia (IL)
 466                             Detroit (MI)
 467                                  Belmont
 468                          Burlington (IA)
 469                                  Madison
 470                                     1848
 471             Wyoming[48]Statehood in 1890
 472                             Yankton (SD)
 473                                 Cheyenne
 474                                     1890

                                                      1  \
 0                                              Capital
 1                                          San AgustÃ­n
 2                                                 1733
 3          Capital of the British Province of Georgia.
 4                    Capitals of the State of Georgia.
 5                                                 1778
 6                                                 1780
 7                                                 1781
 8                                                 1782
 9                                                 1782
 10                                                1784
 11                                                1786
 12                                                1796
 13                                                1798
 14                                                1802
 15                                                1817
 16                                                1819
 17                                                1820
 18                                                1826
 19                                                1846
 20                               Novo-ArkhangelskSitka
 21                Capital of the Department of Alaska.
 22                 Capitals of the District of Alaska.
 23                                                1906
 24                 Capital of the Territory of Alaska.
 25                     Capital of the State of Alaska.
 26                                       Santa Fe (NM)
 27   Capital of the U.S. Territory of New Mexico 18...
 28                                                1862
 29                                                1862
 ..                                                 ...
 445           Capital of the Commonwealth of Virginia.
 446                                               1780
 447                                      Champoeg (OR)
 448                                               1843
 449               Capitals of the Territory of Oregon.
 450                                               1851
 451                                               1853
 452                Capital of the State of Washington.
 453                                     Jamestown (VA)
 454                                               1698
 455         Capital of the British Colony of Virginia.

In [16]:
tabdf = tables[0]
# tabdf.head()
yo = list(tabdf.iloc[0])
yo
#how to turn the first row into header names?

['State',
 'Abr.',
 'State-hood',
 'Capital',
 'Capital since',
 'Area (miÂ²)',
 'Population (2010)',
 'Notes',
 nan,
 nan,
 nan]